apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitcoin-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /ServiceA
        pathType: Prefix
        backend:
          service:
            name: bitcoin-value-a
            port:
              number: 80
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: bitcoin-value-a
            port:
              number: 80
      - path: /ServiceB
        pathType: Prefix
        backend:
          service:
            name: bitcoin-value-b
            port:
              number: 80
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: hello-world-ingress-static
#   namespace: sample
#   annotations:
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/rewrite-target: /static/$2
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /static(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: aks-helloworld-one
#             port:
#               number: 80